name: Execute On Schedule

on:
  schedule:
    - cron: '15 * * * *' # At 15 minutes past each hour (UTC).
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect:
    uses: ./.github/workflows/collect.yml
